# Use root/example as user/password credentials
version: '3.1'

services:

    web:
        build: ./app
        image: dev/totems_app:1.0.1-dev
        container_name: totems-web
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
            - 5555:5555
        environment:
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - mongo
            - redis
            - mosquitto
    
    channel-backend:
        build: ./app
        image: dev/totems_app:1.0.1-dev
        container_name: channel-backend
        command: chasgimqtt -H mosquitto -p 1883 --topic=testmq:2 site_project.asgi:channel_layer -v
        volumes:
            - ./app/:/usr/src/app/
        depends_on:
            - web
    
    workers-server:
        build: ./app
        image: dev/totems_app:1.0.1-dev
        container_name: workers-server
        command: python3 manage.py runworker mqtt
        volumes:
            - ./app/:/usr/src/app/
        depends_on:
            - web
            - channel-backend
    
    celery:
        build: ./app
        image: dev/totems_app:1.0.1-dev
        container_name: celery
        command: celery -A site_project worker -l INFO
        # command: celery -A site_project worker -B -l INFO #ACTIVAR BEAT
        volumes:
            - ./app/:/usr/src/app/        
        depends_on:
            - web
            - redis

    mongo:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - mongo_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: dev_user
            MONGO_INITDB_ROOT_PASSWORD: password

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: dev_user
            ME_CONFIG_MONGODB_ADMINPASSWORD: password

    redis:
        image: redis:alpine
        container_name: redis
        restart: always

    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        restart: always
        volumes:
            - ./mosquitto/data/:/mosquitto/data
            - ./mosquitto/log/:/mosquitto/log
            - ./mosquitto/config/:/mosquitto/config
        # environment:
        #     MOSQUITTO_USERNAME: totems
        #     MOSQUITTO_PASSWORD: 123456789

volumes:
  mongo_data: