# Generated by Django 3.2.4 on 2021-06-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cel',
            field=models.IntegerField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=64),
        ),
    ]
