# Generated by Django 3.2.4 on 2021-06-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210615_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cel',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
