# Generated by Django 3.2.4 on 2021-06-15 00:47

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210615_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cel',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
