# Generated by Django 3.2.4 on 2021-06-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210615_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cel',
        ),
    ]
