# Generated by Django 3.2.4 on 2021-06-19 19:04

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import mqtt_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotemMsg',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('msg', djongo.models.fields.EmbeddedField(model_container=mqtt_app.models.Msg)),
            ],
        ),
    ]
