# Generated by Django 3.2.4 on 2021-06-19 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.CharField(max_length=17, null=True, unique=True)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
