# Generated by Django 3.2.4 on 2021-06-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0002_totem_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='device_id',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='totem',
            name='label',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
