# Generated by Django 3.2.4 on 2021-06-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0003_auto_20210615_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='device_id',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
