# Generated by Django 3.2.4 on 2021-06-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0004_alter_totem_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
