# Generated by Django 3.2.4 on 2021-06-15 01:27

from django.db import migrations
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0005_alter_totem_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='id',
        ),
        migrations.AddField(
            model_name='totem',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
