# Generated by Django 3.2.4 on 2021-06-15 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0006_auto_20210615_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='_id',
        ),
        migrations.AddField(
            model_name='totem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
