# Generated by Django 3.2.4 on 2021-06-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0009_alter_totem_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totem',
            name='device_id',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
