# Generated by Django 3.2.4 on 2021-06-15 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0010_alter_totem_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totem',
            name='device_id',
        ),
    ]
