# Generated by Django 3.2.4 on 2021-06-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totems', '0011_remove_totem_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='totem',
            name='device_id',
            field=models.CharField(default='NA', max_length=17, unique=True),
        ),
    ]
